### ISSUE TITLE
top option does not change glMDSPlot results

### ISSUE THREAD

**Issue by mueggeb** [Shians/Glimma#138]
First, the package is incredibly useful and very well documented. Thank you!

My issue is that the output from glMDSPlot does not change regardless of the value passed to option -top. I'm using Glimma version 1.4.0

# Loaded _rnaseq_ and _groups_ exactly as in Figure 2 of the vignette
# This recreates Figure 2 of the vignette as expected
glMDSPlot(rnaseq, groups=groups)

# Each of these images is exactly the same as Figure 2.  
glMDSplot(rnaseq,top=2,groups=groups)
glMDSPlot(rnaseq, top=5, groups=groups)
glMDSPlot(rnaseq, top=5000,groups=groups)

# Similarly, gene.selection="common" does not seem to change the results
glMDSPlot(rnaseq, gene.selection = "common", groups=groups)

**Comment by Shians** [comment]
Thanks for the report, I know about this and it's similar to #133. I think I've actually fixed this but ended up breaking something in my vignette, so the build is broken until I can figure out how to fix my vignette.

**Comment by mueggeb** [comment]
Thanks for letting me know. The package is really great, we will definitely use it and cite in our research. I’ll watch for the next stable release.
