### ISSUE TITLE
Table in glMDPlot not showing all columns

### ISSUE THREAD

**Issue by jdrnevich** [Shians/Glimma#140]
I just upgraded to the github Glimma version 1.5.1 and now I'm having an issue where the table at the bottom is not showing all the columns. I like to put in longer gene names / descriptions in the table, and the release version of Glimma (1.4.0) would make sure all columns were visible by fixing the widths of all columns and wrapping any longer entries on another line. Now, the column widths change depending on the genes in memory, stretching so all all long entries are on one line. This pushes other columns off to the right, and while there is a slider bar at the bottom, sliding only works on the values in the table and not the table headers, so I can't see nor sort on the missing columns. Plus, if I use the new version and put it in the same folder as a glMDPlot from the old version, it corrupts the old version as well! Screen shots below (hopefully).

I think I'll delete the github version and go back to the release version until this is fixed - the problem with improper rounding of p-values (issue #124) is less bothersome than this, But still an amazing package - thanks so much for it!!!

version 1.4.0, with fixed column sizes and text wrapping:
![image](https://user-images.githubusercontent.com/10635353/29975287-6a843bb2-8efb-11e7-9f00-14b48cfc44dd.png)

version 1.5.1, same genes shown; no text wrapping and adj.P.Val column not visible:
![image](https://user-images.githubusercontent.com/10635353/29975356-9e7bb77e-8efb-11e7-83aa-396b857afccc.png)

version 1.5.1, same as above but scrolled to the right. adj.P.Vals shown in table, but not column headers:
![image](https://user-images.githubusercontent.com/10635353/29975385-cab1872e-8efb-11e7-8086-2048b0cc0d7a.png)

**Comment by Shians** [comment]
Thanks for the feedback, I changed the wrapping inside the table so everything would be on one line, but I guess that had unintended consequences. It's easy to change back and I'll let you know when I've reverted the change.

Also the newer version will "corrupt" old plots if put into the same folder, this is because I made the data storage a bit more efficient by changing the format. This will be a case for all future versions and I'm not sure how to warn people.

**Comment by Shians** [comment]
Have a try with 1.5.2.

**Comment by chodarq** [comment]
Sorry to refloat this issue, but I have the same problem with Glimma 1.17.1, table header didn't change when you scroll. Also, when you select a point in left graphics, no info is displayed in the table.
Thanks.

![1](https://user-images.githubusercontent.com/14064535/88491116-a2a07b80-cf6e-11ea-9a35-1536d394723b.jpg)
![2](https://user-images.githubusercontent.com/14064535/88491118-a92ef300-cf6e-11ea-9378-cda70f0cc7e2.jpg)

**Comment by Shians** [comment]
Thanks for the report and screenshots, I'll look into this.

**Comment by chodarq** [comment]
Hi, thanks for that!.
I have the impression that the problem is related to the annotation columns. I repeat the analysis, without the annotation, and all works just fine.
![3](https://user-images.githubusercontent.com/14064535/88556869-8268cf00-cff7-11ea-96e8-5bff5a8954af.jpg)
