### ISSUE TITLE
bug in glMDPlot.default: internal function make_side_main_unique()

### ISSUE THREAD

**Issue by jdrnevich** [Shians/Glimma#159]
I used glMDPlot to make an interactive volcano plot in R 3.4.3/Glimma 1.6.0 and now the same code is throwing an error in R 3.5/Glimma 1.8.0:
Error in data.frame(anno, x, cols = cols) : 
  arguments imply differing number of rows: 3166, 0

The line that's causing the error is plotting_data <- get_plotting_data(x, anno, cols) but I traced the source of the error back a few lines to the call to make_side_main_unique(). The first if statement contains return(x) so it's returning the data.frame x, not the expected list(x = x, anno = anno). I think if you just remove the return(x) line then it will work. I'm not sure where it lives in your repo, else I'd submit a pull request.

code for make_side_main_unique:
function (x, anno, side.main) 
{
  if (not.null(side.main)) {
    if (side.main %in% colnames(x)) {
      x[[side.main]] <- makeUnique(x[[side.main]])
      return(x)   #REMOVE THIS LINE
    }
    else if (side.main %in% colnames(anno)) {
      anno[[side.main]] <- makeUnique(anno[[side.main]])
    }
  }
  list(x = x, anno = anno)
}

**Comment by Shians** [comment]
Thanks as always for reporting these issues, especially with such detail on where it occurs. I broke this when I decided to be "smarter" with my return values. Fixed in af65caf and propagated to Bioconductor Release in Glimma version 1.8.1.
