### ISSUE TITLE
glMDPlot's transform argument description needs to be changed

### ISSUE THREAD

**Issue by jdrnevich** [Shians/Glimma#160]
Hey - I've been meaning to send this in for a while. In all the glMDPlot functions, the argument transform is described as:

transform   TRUE if counts cpm transformed.

This makes it sounds like you should put TRUE if your counts have already been transformed. It would be much clearer if you put:

transform    TRUE if counts need to be cpm transformed.

**Comment by Shians** [comment]
Good point, don't know why my language was so poor when I wrote that. Fixed in 
e9a002e.
