### ISSUE TITLE
argument to restrict clickable elements

### ISSUE THREAD

**Issue by jmacdon** [Shians/Glimma#59]
For either the MD or volcano plots, it's not very performant with the number of genes on a modern microarray or RNA-Seq analysis. Part of this is because it's loading all the information for genes that are not significantly different, and by definition aren't of interest. 

It would be nice to have the ability to be able to see all the data on the plot, but restrict the tool tips and mapping to the (x,y) plot to just those that are non-zero for the 'status' argument, in order to reduce the loading time for the plot.

**Comment by Shians** [comment]
Thanks for the suggestion, it does seem like a sensible thing to do at least as an option. Though loading time might not dramatically improve without some significant changes in implementation, each point would still need to have all its properties assigned (whether they should be tagged significant or insignificant).

It could improve usage performance if mouse-over events were muted for insignificant points. Will look to implement it when I can.

**Comment by jmacdon** [comment]
It turns out the performance isn't that bad - I was looking at a plot on a remote machine - and if I look at the plot locally it's as fast as I would want.

But if you are still interested, is it possible to just make the insignificant points a big 'smear', sort of like what you get from smoothscatter()? Maybe not worth it, but it might reduce the assigned properties for all those points.
