### ISSUE TITLE
Allow pre-normalized expression values instead of internally computing cpm on counts

### ISSUE THREAD

**Issue by jdrnevich** [Shians/Glimma#61]
I'd like to request the ability to pass the counts argument of glMDPlot a matrix of normalized expression values and turn off the internal computation of cpm values. This would broaden the package to any limma analysis, not just RNA-Seq data. Also, there are times when I'm removing a batch effect from my RNA-Seq data, and I'd like the expression values shown on the right side to also have the batch effect removed. I routinely do this for other visualizations, like heatmaps. Thanks!

**Comment by Shians** [comment]
Being able to turn off the internal computation of CPM values is currently being worked on. It's mostly complete but I haven't come around to fully testing things out.

**Comment by jdrnevich** [comment]
Great! I'll check back every so often...

**Comment by Shians** [comment]
This has been implemented in the form of transform=FALSE, this plots the "counts" as is so you can pre-normalise.
