### ISSUE TITLE
y-axis for the MDplot

### ISSUE THREAD

**Issue by vivekbhr** [Shians/Glimma#63]
Hi @Shians 

Thanks for making this useful package. 

I found that for some of the genes, the logCPM plot (right hand side) of the MDplot doesn't show the values on the y-axis properly. Some problem related to visualization, since the numbers are either stuck to the top or the bottom.I can't figure out what. (examples attached)

![1](https://cloud.githubusercontent.com/assets/8420267/16612398/20b73ee8-4367-11e6-8895-d42fdea2a019.png)
![2](https://cloud.githubusercontent.com/assets/8420267/16612400/23f2d7ca-4367-11e6-9272-96426b8d61d2.png)

**Comment by Shians** [comment]
Thanks for trying out the package!

Would you mind providing the full command for glMDPlot and a head() on the counts matrix you're using?

**Comment by vivekbhr** [comment]
Sure. 

`counts(dds) %>% head()` gives

```
                 cnt_1 cnt_2 cnt_3 cnt_4 DDR19_1 DDR19_2 DDR19_3 DDR19_4 DDR20_1 DDR20_2 DDR20_3 DDR20_4
ENSG00000000003  2942  3571  3122  3008    2199    2068    1766     733    3206    2607    2998    2805
ENSG00000000005    15    15    15    12      49      27      25      13      13      17      21      21
ENSG00000000419  4115  5040  4395  4387    4196    3764    3174    1357    3776    3130    3434    3051
ENSG00000000457   813   888   797   791     689     540     514     208     928     812     818     760
ENSG00000000460  1263  1441  1315  1292    1622    1500    1313     532    1817    1500    1694    1512
ENSG00000000938     1     1     1     3       3       1       1       2       1       0       2       2
```

glMDplot command I used

```
Glimma::glMDPlot(dds, anno = annot, id.column = "Symbol", display.columns = c("GeneID", "Symbol","Description"),samples = samples, groups = groups, main = "Result", status = annot$Category,path = "DESeq_results", folder = "interactive")
```

where `samples` are just `colnames(dds)` and groups are :  `groups <- c(rep("control",4), rep("DDR19",4), rep("DDR20",4))`

**Comment by Shians** [comment]
Thanks, I'll look into it when I can.

**Comment by vivekbhr** [comment]
Also, just want to add that this happens only for some genes. I thought that the cpms are probably very different between the samples to plot them, but i am not sure if this is the case. 

For example, the cpm for gene CYP2E1 from the plot above, is like this..

```
as.matrix(counts(dds)) %>% edgeR::DGEList() %>% edgeR::cpm(log = TRUE) -> test
test["ENSG00000130649",]
```

 gives : 

```

  cnt_1 cnt_2 cnt_3 cnt_4 DDR19_1 DDR19_2 DDR19_3 DDR19_4 
 2.541036114  2.523737336  2.733351224  2.445923700  0.043884314  0.410110960 -0.004704334 -2.576352499 
DDR20_1 DDR20_2 DDR20_3 DDR20_4
 0.478280302  0.289393509  0.937579997  0.911590910 
```

**Comment by Shians** [comment]
Should be fixed.
